### PR TITLE
MODINVOSTO-42 Remove outdated indexes on jsonb->>'foreginKeyId' field

### PR DESCRIPTION
**Pull request by hjiebsco**
## Purpose
MODINVOSTO-42 Remove outdated indexes on jsonb->>'foreginKeyId' field

## Approach
Update schema.json per https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-271

### CODE REVIEW

**Comment by KVupp** [comment]
@hjiebsco We are half way through the release. Are there any effects if these fields are not removed?

**Comment by hjiebsco** [comment]
> @hjiebsco We are half way through the release. Are there any effects if these fields are not removed?

RMB change was introduced in version 27 and mod-invoice-storage is on 29 now. That ticket was created back in September. The risk is very low in my opinion. But if mod-invoice-storage dev team decides not to merge, I can reassign the ticket to one of you, so I can close the core platform umbrella ticket. Let me know.

**Comment by KVupp** [comment]
@hjiebsco , Thanks yes we will take care of merging it after the release. It can make it to the bugfix release if there is one. You can reassign the ticket to me

**Comment by hjiebsco** [comment]
> @hjiebsco , Thanks yes we will take care of merging it after the release. It can make it to the bugfix release if there is one. You can reassign the ticket to me

Done. BTW I removed core platform related tags from the ticket. Please update as needed.

**Pull request merged**
